# Generated by Django 4.2.7 on 2023-11-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_id_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Id',
        ),
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.ForeignKey(db_constraint=False, default='No Author', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author_query', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', primary_key=True, serialize=False),
        ),
    ]
