# Generated by Django 4.2.7 on 2023-11-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_id_alter_post_author_alter_post_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Excert',
            new_name='excerpt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Imagename',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
